import React from 'react';
import { getSession } from '@/lib/auth';
import prisma from '@/lib/db';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import Link from 'next/link';
import { FileText, PlusCircle, Globe, Download, Lock } from 'lucide-react';
import { GenerateReportButton } from './GenerateReportButton';

export default async function ReportsPage() {
  const session = await getSession();
  if (!session || !session.currentSocietyId) {
    return <div className="p-8 text-center text-slate-500">Please select a society.</div>;
  }

  const societyId = session.currentSocietyId;
  const isManager = ['TREASURER', 'FACULTY_COORDINATOR', 'SOCIETY_ADMIN', 'SUPER_ADMIN'].includes(
    session.currentSocietyRole || ''
  );

  const [reports, activeFy] = await Promise.all([
    prisma.report.findMany({
      where: { societyId },
      include: {
        financialYear: true,
        generatedBy: { select: { name: true } },
      },
      orderBy: { generatedAt: 'desc' },
    }),
    prisma.financialYear.findFirst({
      where: { societyId, isCurrent: true },
    }),
  ]);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-sky-600" />
            <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Financial Reports</h1>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Audit-certified statements, annual audits, and published transparency disclosures
          </p>
        </div>

        {isManager && activeFy && (
          <GenerateReportButton societyId={societyId} financialYearId={activeFy.id} />
        )}
      </div>

      {/* Reports List */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-2xs overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-600 border-b border-slate-200 uppercase tracking-wider text-[11px]">
              <tr>
                <th className="py-3 px-4">Report Number</th>
                <th className="py-3 px-4">Title</th>
                <th className="py-3 px-4">Type</th>
                <th className="py-3 px-4">Financial Year</th>
                <th className="py-3 px-4">Generated By</th>
                <th className="py-3 px-4">Generated Date</th>
                <th className="py-3 px-4 text-center">Visibility</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {reports.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-12 text-center text-slate-400">
                    No official report snapshots generated yet. Click &quot;Generate New Report&quot; to compile.
                  </td>
                </tr>
              ) : (
                reports.map((r) => (
                  <tr key={r.id} className="hover:bg-slate-50/70 transition-colors">
                    <td className="py-3.5 px-4 font-semibold text-slate-900">
                      <Link href={`/reports/${r.id}`} className="hover:text-sky-600">
                        {r.reportNumber}
                      </Link>
                    </td>
                    <td className="py-3.5 px-4 font-medium text-slate-800">{r.title}</td>
                    <td className="py-3.5 px-4 text-slate-600">
                      <span className="px-2 py-0.5 rounded bg-slate-100 font-semibold text-[10px]">
                        {r.reportType}
                      </span>
                    </td>
                    <td className="py-3.5 px-4 text-slate-600">{r.financialYear.name}</td>
                    <td className="py-3.5 px-4 text-slate-600">{r.generatedBy.name}</td>
                    <td className="py-3.5 px-4 text-slate-500">
                      {new Date(r.generatedAt).toLocaleDateString()}
                    </td>
                    <td className="py-3.5 px-4 text-center">
                      {r.isPublic ? (
                        <span className="inline-flex items-center gap-1 text-[11px] text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200 font-medium">
                          <Globe className="w-3 h-3" />
                          Public
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 text-[11px] text-slate-600 bg-slate-100 px-2 py-0.5 rounded-full border border-slate-200 font-medium">
                          <Lock className="w-3 h-3" />
                          Internal
                        </span>
                      )}
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      <Link
                        href={`/reports/${r.id}`}
                        className="px-2.5 py-1 rounded bg-sky-50 hover:bg-sky-100 text-sky-700 font-semibold text-xs"
                      >
                        Inspect
                      </Link>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
